repos:
  ##############################################################################
  #  General checks
  ##############################################################################
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: forbid-new-submodules
      - id: fix-encoding-pragma
        args: [--remove]
      - id: end-of-file-fixer
        types_or: [python, cython, rust]
      - id: trailing-whitespace
        types_or: [rust, cython, python]
      - id: debug-statements
      - id: detect-private-key
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        description: Checks for common misspellings.
        types_or: [python, cython, rst, markdown]
        args: ["-L", "crate,ot,zar"]
